### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by vonDowntown** [binogure-studio/gdlinter#3]
Hey,
so i noticed that in this repository no license is present. As a result no one is allowed to use your code the only right that is given is to view everything. 
Please take a look at:
- https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
- https://choosealicense.com/ 
 
And then decide.

Because you are using MIT and GPLv3 on other projects, I propose to use one of them.

**Comment by xsellier** [comment]
Hey,

I haven't noticed! Thank you for the report, and I put a MIT LICENSE file.
